### ISSUE TITLE
On web pages some emojis are replaced by a question mark

### ISSUE THREAD

**Issue by agilare** [agilare/ladecadanse#40]
Example : https://ladecadanse.darksite.ch/evenement.php?idE=182721
Original text : https://www.facebook.com/events/1027089037496463/

**Comment by a-mango** [comment]
This is a database encoding related issue. Newer emojis such as 🔮 use the full 4 unicode bytes while older ones like ✨ only need 3 of them. Our problem here arises because the [sql database](https://github.com/agilare/ladecadanse/blob/0c976a24dc9e110be3f782786c769f807c4fc502/ladecadanse.sql#L33) and [PHP connector](https://github.com/agilare/ladecadanse/blob/0c976a24dc9e110be3f782786c769f807c4fc502/librairies/DbConnector.php#L34) use the badly named `utf8` charset (which [only supports a maximum of three bytes per multibyte character](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html)) instead of the recommended `utf8mb4` charset which offers real Unicode support.

The following changes have to be made to fix the problem : 

- Modify the source code to use the `utf8mb4` charset in database connections (see [https://www.php.net/manual/en/mysqli.set-charset.php](https://www.php.net/manual/en/mysqli.set-charset.php)
- Modify the existing database schema to use the same `utf8mb4` chartset. This involves making changes on the production database. See [this write-up](https://mathiasbynens.be/notes/mysql-utf8mb4).

**Comment by agilare** [comment]
I just deployed this fix on prod (I needed to wait a sysadmin intervention) and it works fine, I amended the [example event "Disco Voodoo"](https://ladecadanse.darksite.ch/evenement.php?idE=182721)  !
Thank you very much @a-mango !
